name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate ZIP
        run: zip -r module.zip . -x ".git/*" ".github/*" ".gitignore" "assets/" "wiki/"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            module.zip
            module.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Module to FoundryVTT Website
        id: publish-to-foundry-website
        uses: cs96and/FoundryVTT-release-package@v1
        with:
          package-token: ${{ secrets.FOUNDRY_TOKEN }}
          manifest-url: https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/module.json
          notes-url: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}
